#!/bin/bash

echo "============ RUN SPECIAL SCRIPT ================="
echo ""
which wkhtmltopdf
echo ""
go tool cgo -gccgo wkhtmltopdf/pdf_c_api.go 
echo ""
ls -l _obj
echo ""
echo "============ RUN GO FMT ================="
echo ""
for d in `find . -name \*.go -exec dirname {} \; | grep -v vendor/ | grep -v .gosrc/|sort -u`;do go fmt ${d}/*.go; done
echo ""
echo "============ END SPECIAL SCRIPT ================="
echo ""
echo ""
echo "============= RUN COMMON SCRIPT ================="
/var/lib/jenkins/common/script/cibuild
keepstatus=$?
echo " ----------- status = $keepstatus ---------------"
echo "============= END COMMON SCRIPT ================="
exit $keepstatus
